package com.hframework.web.config.bean.program;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("template")
public class Template   {

	@XStreamAlias("path")
	private String path;

    public Template() {
    }
   
 	 	 
     public String getPath(){
     	return path;
     }

     public void setPath(String path){
     	this.path = path;
     }
	 
}
