package com.hframework.web.config.bean.module;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("component")
public class Component   {

	@XStreamImplicit
    @XStreamAlias("event")
	private List<Event> eventList;
	@XStreamAsAttribute
    @XStreamAlias("id")
	private String id;
	@XStreamAsAttribute
    @XStreamAlias("data-set")
	private String dataSet;
	@XStreamAsAttribute
    @XStreamAlias("dataid")
	private String dataid;

    public Component() {
    }
   
 	 	 
     public List<Event> getEventList(){
     	return eventList;
     }

     public void setEventList(List<Event> eventList){
     	this.eventList = eventList;
     }
	 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getDataSet(){
     	return dataSet;
     }

     public void setDataSet(String dataSet){
     	this.dataSet = dataSet;
     }
	 	 	 
     public String getDataid(){
     	return dataid;
     }

     public void setDataid(String dataid){
     	this.dataid = dataid;
     }
	 
}
