package com.hframework.web.config.bean.component;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("event")
public class Event   {

    @XStreamAlias("attach")
	private Attach attach;
    @XStreamAlias("source")
	private Source source;
    @XStreamImplicit
    @XStreamAlias("effect")
	private List<Effect> effectList;
	@XStreamAsAttribute
    @XStreamAlias("id")
	private String id;
	@XStreamAsAttribute
    @XStreamAlias("type")
	private String type;
	@XStreamAsAttribute
    @XStreamAlias("name")
	private String name;

    public Event() {
    }


    public Attach getAttach() {
        return attach;
    }

    public void setAttach(Attach attach) {
        this.attach = attach;
    }

    public Source getSource() {
        return source == null ? new Source() : source;
    }

    public void setSource(Source source) {
        this.source = source;
    }

    public List<Effect> getEffectList(){
     	return effectList;
     }

     public void setEffectList(List<Effect> effectList){
     	this.effectList = effectList;
     }
	 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 
}
